from pathlib import Path
import ast

p=Path(__file__).with_name('app.py')
s=p.read_text()
ast.parse(s)
assert "DATABASE_URL=os.getenv('DATABASE_URL','').strip()" in s
assert "import psycopg" in s
assert "psycopg.connect(DATABASE_URL, row_factory=dict_row)" in s
assert "GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in s
assert "INSERT OR IGNORE INTO enrollments" not in s
assert "SELECT last_insert_rowid()" in s  # SQLite fallback only
assert "if not DATABASE_URL:" in s
assert "Zapowiedziane sprawdziany" in s
assert "behavior_value" in s
assert "calendar_events" in s
print('STATIC POSTGRES V4.6.1 CHECKS PASSED')
